import Head from "next/head";
import React, { useState, useContext, useLayoutEffect, useEffect } from "react";
import Aside from "../engine/component/Aside/Aside";
import Masonry from "../engine/component/Masonry/Masonry";
import S from "../styles/Home.module.scss";

export default function Home() {
  const [params, setParams] = useState({
    column: 4,
    gap: "1rem",
    width: "1330",
  });

  function handleChange(e, fields) {
    console.log(e.target.value, fields);
    let val = e.target.value;

    if (fields === "gap") {
      val = e.target.value + "rem";
    }

    setParams((S) => ({ ...S, [`${fields}`]: val }));
  }
  return (
    <div className={S.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={S.main}>
        <Aside>
          <div className={S.bloc_input_col}>
            <label htmlFor="column">Columns</label>
            <input
              defaultValue={params.column}
              min="1"
              id="column"
              type="number"
              onChange={(e) => {
                handleChange(e, "column");
              }}
            />
          </div>

          <div className={S.bloc_input_col}>
            <label htmlFor="gap">Gap (rem)</label>
            <input
              defaultValue={1}
              min="1"
              step=".5"
              id="gap"
              type="number"
              onChange={(e) => {
                handleChange(e, "gap");
              }}
            />
          </div>

          <div className={S.bloc_input_col}>
            <label htmlFor="width">Width (px)</label>
            <input
              defaultValue={params.width}
              min="360"
              id="width"
              type="number"
              onChange={(e) => {
                handleChange(e, "width");
              }}
            />
          </div>
        </Aside>

        <Masonry
          dir="assets/img/masonry/"
          masonry={{
            column: params.column,
            gap: params.gap,
            width: `${params.width}px`,
          }}
          horizontalPadding="1rem"
        ></Masonry>
      </main>
    </div>
  );
}
