import Head from "next/head";
import React, { useState, useContext, useLayoutEffect, useEffect } from "react";
import Masonry from "../engine/component/Masonry/Masonry";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [params, setParams] = useState({
    column: 4,
    gap: "0.5rem",
    width: "1330",
  });

  function handleChange(e, fields) {
    console.log(e.target.value, fields);
    let val = e.target.value;

    if (fields === "gap") {
      val = e.target.value + "rem";
    }
    if (fields === "width") {
      val = e.target.value + "px";
    }

    setParams((S) => ({ ...S, [`${fields}`]: val }));
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header>
          <h1 className={styles.title}>Mansonry Grid demo</h1>
        </header>
        <div className={styles.description}>
          <h1>Project info</h1>
          <p>Framework : Next.js</p>

          <div>
            <label htmlFor="column">Number of columns</label>
            <input
              defaultValue={params.column}
              min="1"
              id="column"
              type="number"
              onChange={(e) => {
                handleChange(e, "column");
              }}
            />
          </div>

          <div>
            <label htmlFor="gap">Gap</label>
            <input
              defaultValue={1}
              min="1"
              step="1"
              id="gap"
              type="number"
              onChange={(e) => {
                handleChange(e, "gap");
              }}
            />
          </div>

          <div>
            <label htmlFor="width">Masonry width</label>
            <input
              defaultValue={params.width}
              min="360"
              id="width"
              type="number"
              onChange={(e) => {
                handleChange(e, "width");
              }}
            />
          </div>
        </div>
        <Masonry
          dir="assets/img/masonry/"
          masonry={{
            column: params.column,
            gap: params.gap,
            width: `${params.width}px`,
          }}
          horizontalPadding="1rem"
        ></Masonry>
      </main>
    </div>
  );
}
